//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JooleApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblType
    {
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public string TypeOption { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<int> SubcategoryID { get; set; }
    
        public virtual tblProduct tblProduct { get; set; }
        public virtual tblSubcategory tblSubcategory { get; set; }
    }
}
